const shopManageData = [
  {
    Id: 1,
    Name: "风华电子店铺",
    Account: "selleradmin",
    ShopGrade: "Platinumstore",
    EndDate: "2068-01-01",
    Status: "开启",
    IsSelf: true,
    BusinessCategory: null,
    CompanyName: null,
    CompanyRegion: null,
    CompanyAddress: null,
    CompanyPhone: null,
    CompanyEmployeeCount: 0,
    CompanyRegisteredCapital: 0,
    ContactsName: null,
    ContactsPhone: null,
    ContactsEmail: null,
    BusinessLicenceNumber: null,
    BusinessLicenceNumberPhoto: null,
    BusinessLicenceRegionId: null,
    BusinessLicenceStart: null,
    BusinessLicenceEnd: null,
    BusinessSphere: null,
    OrganizationCode: null,
    OrganizationCodePhoto: null,
    GeneralTaxpayerPhot: null,
    BankAccountName: null,
    BankAccountNumber: null,
    BankName: null,
    BankCode: null,
    BankRegionId: null,
    BankPhoto: null,
    TaxRegistrationCertificate: null,
    TaxpayerId: null,
    TaxRegistrationCertificatePhoto: null,
    PayPhoto: null,
    PayRemark: null,
    BusinessLicenseCert: null,
    ProductCert: null,
    OtherCert: null,
    legalPerson: null,
    CompanyFoundingDate: null,
    CompanyRegionId: 0,
    NewBankRegionId: 0,
    BusinessType: 0,
    IDCard: null,
    IDCardUrl: null,
    IDCardUrl2: null,
    WeiXinNickName: null,
    WeiXinSex: 0,
    WeiXinAddress: null,
    WeiXinTrueName: null,
    WeiXinImg: null,
    WeiXinOpenId: null,
    ShopBranchCount: 49,
    Balance: 10091.75,
    data: [
      {
        Id: 0,
        leimu: '茶盘>木制茶盘>木制',
        bili: '1.00'
      },
      {
        Id: 1,
        leimu: '茶盘>乌金石茶盘>乌金石茶盘',
        bili: '2.00'
      }
    ]
  }
]
export default shopManageData

